name: Run Python Script Every 4 Hours

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:  # Optional: allows manual triggering from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas numpy ccxt

      - name: Run Python script with secrets
        env:
          API: ${{ secrets.API }}
          SECRET: ${{ secrets.SECRET }}
        run: python run.py
